name: TF Infra Cleanup

on:
  workflow_dispatch:

jobs:
  InfraProvision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.8.4'

      - name: Destroy Configuration
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform init
          terraform plan -var-file="prod.tfvars" -destroy -out terraform.plan
          terraform apply -auto-approve terraform.plan